### ISSUE TITLE
Relation to jsontableschema-infer-js

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/jsontableschema-js#14]
@pwalsh wondering about relationship with https://github.com/frictionlessdata/jsontableschema-infer-js

Has this lib superseded that one and if so could we get some code samples (cf #6)?

**Comment by pwalsh** [comment]
This library supersedes that one. If you can add me as an owner on it, I can add a deprecation warning with `npm deprecate`. Docs will come with #6. I'll leave this open until I can add the deprecation warning.

**Comment by pwalsh** [comment]
Closing in favour of #18
