### ISSUE TITLE
Deprecate json-table-schema-validator

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/jsontableschema-js#17]
# Description

Requires https://github.com/frictionlessdata/jsontableschema-js/issues/16

The `validate` module here replaces https://github.com/okfn/json-table-schema-validator
# Tasks
- [x] Check that this lib covers all functionality of that lib (and implement what is missing, after first describing what is missing here in a comment)
- [x] Issue a deprecation warning on that lib ( check with @pwalsh on how to do that )

**Comment by roll** [comment]
@pwalsh 
ping)

> Issue a deprecation warning on that lib ( check with @pwalsh on how to do that )

**Comment by pwalsh** [comment]
@roll 

I just gave you access to this lib (and many others) on NPM.

Can you do this please:

https://docs.npmjs.com/cli/deprecate

**Comment by roll** [comment]
@pwalsh 
ok

**Comment by roll** [comment]
DONE
`npm WARN deprecated json-table-schema-validator@0.1.0: please use jsontableschema`
