### ISSUE TITLE
Implement cli

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/jsontableschema-js#3]
https://github.com/frictionlessdata/jsontableschema-py/blob/master/jsontableschema/cli.py

Using a suitable high-level command line builder like commander: https://www.npmjs.com/package/commander

**Comment by rgrp** [comment]
What about just doing this as part of `dpm` for now.

**Comment by pwalsh** [comment]
WONTFIX. All CLI interfaces for js will be consolidated in DPM. See https://github.com/frictionlessdata/dpm/issues/53
