### ISSUE TITLE
Documentation improvement suggestions

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/jsontableschema-js#30]
First, well done on the new docs - great to have those.

I make one general point and then a few suggestions.

General point: **who is your audience**? Reading this it seems often to be another developer *working on the library*. However, my guess is the vast majority of readers are users of this lib who won't be hacking on it any time soon. So I think you should focus docs here and elsewhere on users and keep info for other contributors in a section at the bottom.

Why is this important? I'll illustrate with just two examples:

* The "Goals" section: this only really relevant to other contributors to the lib. I'd delete this or move this to a "Hacking" section at the bottom of the README if your focus is users.
* Tone and approach: for users I'd make this terser and bring the key methods to the top. Lengthy documentation of the object model could move down. As it is currently, the README is quite comprehensive on general technical details e.g. how casting works, what types there are etc that are the kind of things users would only want if they had a problem.

Here are a few suggestions:

* Installation: Clarify whether you can use this in the browser too
* Goals: I would move this to the very end personally - this is for people hacking on the library not for peo
* QuickStart: most people looking at this are devs who just want to get started. Show me quickly what are the main methods I am likely to use. IMO these are:
  * `infer`
  * `validate`
* Your examples seem to use ES6 only import syntax. That's quite an assumption for most average JS users atm.

**Comment by zhenyab** [comment]
Thank you for review and suggestions. Make sense!

**Comment by roll** [comment]
DOCS are improved via various changes in:
- https://github.com/frictionlessdata/jsontableschema-js/commit/313af47a1ea66bb6414231201c767fb77c0a909f
- https://github.com/frictionlessdata/jsontableschema-js/commit/c54c82074b2cdf31ef9463859d39faec6271da2e
- https://github.com/frictionlessdata/jsontableschema-js/commit/d8add49501f76251e6df80b3cb262f5874674553
