### ISSUE TITLE
Reason for dates being moment objects?

### ISSUE THREAD

**Issue by Hypercubed** [frictionlessdata/jsontableschema-js#33]
I'm giving jsontableschema-js a try in a project, I'm surprised that the 'data' type returns moment objects.  Any reason not to return JS date objects?  If you are using moment just for parsing how about returning the `.toDate()` output.

**Comment by pwalsh** [comment]
Hi @Hypercubed 

After thinking about this a bit, I'm quite partial to leaving it as moment objects. The user can easily get a date string by calling `toDate`, but they also get the flexibility to use other methods on moment.

Apart from this being undocumented, which is easily fixed, can you describe a use case where it is restricting to be provided with a moment object?

**Comment by roll** [comment]
@akariv 
WDYT? 

It feels a little bit wrong for me when a core lib like `jsontableschema` have such a dependency on API level.

**Comment by Hypercubed** [comment]
@pwalsh My idea is to use this module to transform table data to data types usable within JS applications; for example in angular or d3 applications.  These, typically, expect the date type to be a JS native `Date`.  If I need to perform a second transform after the schema transform to convert moment objects to native Date objects this kind of defeats the purpose.  Anyway, that is just my opinion.

**Comment by roll** [comment]
@zhenyab 
Use native `Date` seems the safest way for me based on this and many other we don't know for now. WDYT?

**Comment by pwalsh** [comment]
If we call native date, we actually also should ensure it is cast to the right format.

**Comment by zhenyab** [comment]
Native Date object has poor API, and moment object provide much more possibilities to work with the date. What the reason then to have it as JS native Date object? Need to see real use case and real usage examples to understand what will be better to return.

**Comment by Hypercubed** [comment]
Yes, moment has a better API and it makes sense to produce moment objects, however, not many API consume moment objects.  I think the purpose of using the schema transform is to generate data that is coconsable by other applications. If you are casting to moment objects then using the data in an angular application (maybe ui-grid for example) or a d3 chart (using d3 time scale) you will need to convert the moment object to a Date object.  I think this is a real world use case.

**Comment by Hypercubed** [comment]
Here is an example of where I would need to convert the moment object to a date object for use by both angular and d3:  http://hypercubed.github.io/Project-Chi/#/examples/universe

(note this is using https://github.com/Hypercubed/chi-datapackage , not jsontableschema-js, in part for this reason).
