### ISSUE TITLE
Automate release procedure

### ISSUE THREAD

**Issue by roll** [frictionlessdata/jsontableschema-js#37]
# Overview

We need to release on npm automatically on new tags adding by GitHub release system - https://github.com/frictionlessdata/jsontableschema-js/releases

**Comment by roll** [comment]
@pwalsh 
do we need your help here or we have enough?

**Comment by pwalsh** [comment]
dont need me. whatever you say boss :)

**Comment by roll** [comment]
@pwalsh 
I mean credentials, maintainer status on npm, encrypted password as for pypi etc?

**Comment by pwalsh** [comment]
it should all work just like we do for pypi. you can publish, and then share it with zhenyab, me and okfn

**Comment by roll** [comment]
@pwalsh 
but we already have one - https://www.npmjs.com/package/jsontableschema (I'm `roll` on npm)

**Comment by pwalsh** [comment]
i know. so what is the question? i'm lost.

**Comment by roll** [comment]
@pwalsh 
It's ok now nevermind. @zhenyab has added me to the maintainers.
