### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/jsontableschema-js#6]
#  Description

Requires https://github.com/frictionlessdata/jsontableschema-js/issues/15 and https://github.com/frictionlessdata/jsontableschema-js/issues/16

This lib started as a port of https://github.com/frictionlessdata/jsontableschema-py, to get our support for http://dataprotocols.org/json-table-schema/ up-to-date. However, only the parts needed for a particular project where implemented, and the documentation was not done.

After we update the library to release `0.2.0`, we need to document the main methods. Again, the [Python README](https://github.com/frictionlessdata/jsontableschema-py/blob/master/README.md) is in great shape, so use that as a template for documenting this lib.

# Tasks

- [x] Goals
- [x] Installation
- [x] Component: Model
- [x] Component: Types
- [x] Component: Infer
- [x] Component: Validate
- [x] Contributing

**Comment by rgrp** [comment]
@pwalsh bump! I'd even start to have a rule that you can't have a repo on github without a basic README summarizing purpose, installation and some sample code :wink:

**Comment by pwalsh** [comment]
We already do have it as a 'rule' in our new coding standards but there are so many code bases that ore date that (Feb 2016) which will only be updated when we work on them again.

**Comment by rgrp** [comment]
@pwalsh can i bump this one as a priority as it relates to #14 - even if someone who has worked on this spent 15m just documenting the main methods.

**Comment by pwalsh** [comment]
DONE.
